spring:
  jwt:
    secret: f7c58b36-3950-4c40-a5ad-65e87ecda293

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1087015527840-s1tn1gstbpuco10g31pvlu50cjvhhfsb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile